// server-https.js
const fs = require( 'fs' );
const https = require( 'https' );
const path = require( 'path' );

// Import the Express app from index.js
const app = require( './index' );

// Certificates generated by mkcert (make sure filenames match)
const keyPath = path.join( __dirname, '192.168.1.9+1-key.pem' );
const certPath = path.join( __dirname, '192.168.1.9+1.pem' );

if ( !fs.existsSync( keyPath ) || !fs.existsSync( certPath ) )
{
    console.error( 'Certificate or key not found. Make sure 192.168.1.9+1-key.pem and 192.168.1.9+1.pem are in the project folder.' );
    process.exit( 1 );
}

const key = fs.readFileSync( keyPath );
const cert = fs.readFileSync( certPath );

const PORT = 3000;
const HOST = '0.0.0.0';

https.createServer( { key, cert }, app ).listen( PORT, HOST, () =>
{
    console.log( `HTTPS server running at https://${ require( 'os' ).hostname() }:${ PORT } (listening on ${ HOST }:${ PORT })` );
    console.log( `Access by IP: https://192.168.1.9:${ PORT }` );
} );
